<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Versta.Orders.Projection.Worker-34965a9a-5cf2-4ebf-9131-098f66b49359</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Versta.Orders.Domain\Versta.Orders.Domain.csproj" />
    <ProjectReference Include="..\Versta.Orders.Application\Versta.Orders.Application.csproj" />
    <ProjectReference Include="..\Versta.Orders.Infrastructure\Versta.Orders.Infrastructure.csproj" />
  </ItemGroup>
</Project>
